//Plans
export const FETCH_PLANS = 'FETCH_PLANS';
export const FETCH_PLANS_FULFILLED = 'FETCH_PLANS_FULFILLED';
export const FETCH_PLANS_REJECTED = 'FETCH_PLANS_REJECTED';
export const SET_SELECTED_PLAN = 'SET_SELECTED_PLAN';
export const SET_GAZED_PLAN = 'SET_GAZED_PLAN';

//Devices
export const FETCH_DEVICES = 'FETCH_DEVICES';
export const FETCH_DEVICES_FULFILLED = 'FETCH_DEVICES_FULFILLED';
export const FETCH_DEVICES_REJECTED = 'FETCH_DEVICES_REJECTED';
export const SET_SELECTED_DEVICE = 'SET_SELECTED_DEVICE';
export const SET_GAZED_DEVICE = 'SET_GAZED_DEVICE';
export const SET_SELECTED_DEVICE_COLOR = 'SET_SELECTED_DEVICE_COLOR';
export const FETCH_SELECTED_DEVICE = 'FETCH_SELECTED_DEVICE';
export const SET_GAZED_DEVICE_COLOR = 'SET_GAZED_DEVICE_COLOR';



//export const SET_CURRENT_POST = 'set_current_post';